import {test,expect} from '@playwright/test';
import 'dotenv/config';
test('existing frontend: login, navigation, CRUD, report, graph, engines, mobile, logout',async({page})=>{
 const errors:string[]=[];page.on('pageerror',e=>{errors.push(e.message);console.log('BROWSER ERROR:',e.message)});
 await page.goto('/');await page.getByLabel('Email',{exact:true}).fill('admin@gram-pulse.demo');await page.getByLabel('Password',{exact:true}).fill(process.env.SEED_PASSWORD!);await page.getByRole('button',{name:'Sign in',exact:true}).click();await expect(page.locator('#serviceOverlay')).toHaveCount(0);
 await expect(page.locator('#kpis')).toContainText('VILLAGE PULSE');await page.screenshot({path:'test-results/dashboard.png',fullPage:true});
 for(const id of ['twin','priorities','assets','incidents','reports','analytics','confidence','settings','management','audit','brief','citizen']){await page.locator(`#nav [data-page="${id}"]`).click();await expect(page.locator('#'+id)).toBeVisible();}
 await page.locator('#nav [data-page="assets"]').click();await page.getByRole('button',{name:'＋ Add asset',exact:true}).click();await page.locator('#fName').fill('Browser smoke asset');await page.locator('#fCondition').fill('60');await page.getByRole('button',{name:'Save asset',exact:true}).click();await expect(page.locator('#modal')).not.toHaveClass(/show/);await page.locator('#assetSearch').fill('Browser smoke asset');await expect(page.locator('#assetRows')).toContainText('Browser smoke asset');await page.reload();await expect(page.locator('#serviceOverlay')).toHaveCount(0);await page.locator('#assetSearch').fill('Browser smoke asset');await expect(page.locator('#assetRows')).toContainText('Browser smoke asset');
 await page.locator('#nav [data-page="simulate"]').click();await page.getByRole('button',{name:/Run.*simulation/i}).first().click();await expect(page.locator('#simulationResult')).toContainText('Residents affected');await expect(page.locator('#simulationResult')).toContainText('Primary Health');
 await page.locator('#nav [data-page="budget"]').click();await page.getByRole('button',{name:/Generate.*plan/i}).first().click();await expect(page.locator('#planRows')).toContainText('priority');
 await page.locator('#nav [data-page="whatif"]').click();await expect(page.locator('#whatIfResults')).toContainText('before → after');
 await page.locator('#nav [data-page="citizen"]').click();await page.locator('#citizenDescription').fill('Browser test: blocked drain and waterlogging in Ward 4');await page.locator('#citizenWard').selectOption('4');await page.locator('#citizenAsset').selectOption('D04');await page.getByRole('button',{name:'Submit report',exact:true}).click();await expect(page.locator('#modalTitle')).toContainText('Report recorded');await page.locator('.modal-x').click();
 await page.setViewportSize({width:390,height:844});await page.evaluate(()=>window.scrollTo(0,0));await page.screenshot({path:'test-results/mobile.png',fullPage:true});expect(await page.evaluate(()=>document.documentElement.scrollWidth<=window.innerWidth+2)).toBeTruthy();
 await page.locator('#accountLabel').click();await page.getByRole('button',{name:'Sign out',exact:true}).click();await expect(page.locator('#loginForm')).toBeVisible();expect(errors).toEqual([]);
});
test('citizen permissions, own reports, protected deep link and service retry',async({page})=>{
 await page.goto('/#citizen');await page.getByLabel('Email',{exact:true}).fill('citizen@gram-pulse.demo');await page.getByLabel('Password',{exact:true}).fill(process.env.SEED_PASSWORD!);await page.getByRole('button',{name:'Sign in',exact:true}).click();await expect(page.locator('#serviceOverlay')).toHaveCount(0);await expect(page.locator('#citizen')).toBeVisible();await expect(page.locator('#nav [data-page="management"]')).toBeHidden();
 const denied=await page.request.get('/api/users');expect(denied.status()).toBe(403);
 await page.goto('/#management');await expect(page.locator('#modalTitle')).toContainText('Access restricted');await page.locator('.modal-x').click();
 await page.route('**/api/state',route=>route.abort());await page.reload();await expect(page.locator('#serviceOverlay')).toContainText('Unable to connect');await page.unroute('**/api/state');await page.getByRole('button',{name:'Retry',exact:true}).click();await expect(page.locator('#serviceOverlay')).toHaveCount(0);
});
