import {test} from 'node:test';
import assert from 'node:assert/strict';
import {mkdtemp,mkdir} from 'node:fs/promises';
import path from 'node:path';
import sharp from 'sharp';
await mkdir('data/tests',{recursive:true});
process.env.DATA_DIR=await mkdtemp(path.resolve('data/tests/run-'));
process.env.NODE_ENV='test';process.env.SEED_PASSWORD='Integration-test-password-2026';delete process.env.DATABASE_URL;
const {connect,migrate}=await import('../server/db.js');
const {seed}=await import('../server/seed.js');
const {createApp}=await import('../server/app.js');
const {rice,optimize,whatIf}=await import('../server/engines.js');
const {snapshot}=await import('../server/services.js');
type Json=Record<string,unknown>;
test('database, sessions, RBAC, CRUD, evidence, engines and durable records',async t=>{
 let db=await connect();await migrate(db);await seed(db);await migrate(db);assert.equal(await seed(db),false);
 const server=createApp(db).listen(0,'127.0.0.1');await new Promise<void>(r=>server.once('listening',r));const address=server.address();assert.ok(address&&typeof address!=='string');const base='http://127.0.0.1:'+address.port;
 const sessions=new Map<string,{cookie:string;csrf:string}>();
 async function call(route:string,method='GET',body?:unknown,role='admin'){const s=sessions.get(role);const res=await fetch(base+'/api'+route,{method,headers:{'Content-Type':'application/json',...(s?{Cookie:s.cookie,'X-CSRF-Token':s.csrf}:{})},body:body===undefined?undefined:JSON.stringify(body)});const json=await res.json() as {data:Json;success:boolean;error:{code:string;message:string}};return{res,...json}}
 try{
 await t.test('authentication / CSRF / role gates',async()=>{assert.equal((await call('/state')).res.status,401);assert.equal((await call('/auth/login','POST',{email:'admin@gram-pulse.demo',password:'wrong'})).res.status,401);for(const role of ['admin','officer','citizen']){const r=await call('/auth/login','POST',{email:role+'@gram-pulse.demo',password:process.env.SEED_PASSWORD},role);assert.equal(r.res.status,200);sessions.set(role,{cookie:r.res.headers.get('set-cookie')!.split(';')[0],csrf:String(r.data.csrf)});}assert.equal((await call('/users','GET',undefined,'citizen')).res.status,403);const res=await fetch(base+'/api/assets',{method:'POST',headers:{Cookie:sessions.get('admin')!.cookie,'Content-Type':'application/json'},body:'{}'});assert.equal(res.status,403);assert.equal((await call('/assets','POST',{},'officer')).res.status,403)});
 const admin={id:'admin',villageId:'adarsh',name:'Admin',email:'admin@gram-pulse.demo',role:'admin' as const,disabled:false};
 let assetId='',reportId='';
 await t.test('asset CRUD, validation, relational constraints and page filters',async()=>{const r=await call('/assets','POST',{name:'Integration drain',type:'Drainage',ward:4,condition:55,pop:300,cost:.5,hazard:65,action:'Inspect test drain'});assert.equal(r.res.status,201,JSON.stringify(r));assetId=String(r.data.id);assert.equal((await call('/assets/'+assetId,'PATCH',{condition:30})).res.status,200);assert.equal((await call('/assets/'+assetId)).data.condition,30);assert.equal((await call('/assets/'+assetId,'PATCH',{condition:-1})).res.status,400);assert.equal((await call('/assets?ward=4&q=Integration&pageSize=1')).res.status,200);assert.equal((await call('/dependencies','POST',{source:assetId,target:'missing',type:'protects'})).res.status,404);const edge=await call('/dependencies','POST',{source:assetId,target:'R07',type:'protects'});assert.equal(edge.res.status,201);assert.equal((await call('/dependencies','POST',{source:assetId,target:'R07',type:'protects'})).res.status,409);});
 await t.test('image content validation and report-to-pulse / priority flow',async()=>{const before=(await snapshot(db,admin));const buffer=await sharp({create:{width:16,height:16,channels:3,background:'#176b4c'}}).png().toBuffer();const s=sessions.get('citizen')!;const upload=await fetch(base+'/api/uploads',{method:'POST',headers:{Cookie:s.cookie,'X-CSRF-Token':s.csrf,'Content-Type':'image/png'},body:new Uint8Array(buffer)});assert.equal(upload.status,201);const u=await upload.json() as {data:{id:string}};const invalid=await fetch(base+'/api/uploads',{method:'POST',headers:{Cookie:s.cookie,'X-CSRF-Token':s.csrf,'Content-Type':'image/png'},body:'not an image'});assert.equal(invalid.status,400);const r=await call('/reports','POST',{category:'Drainage',description:'Blocked integration drain with unsafe flooding',ward:4,assetId,imageId:u.data.id},'citizen');assert.equal(r.res.status,201,JSON.stringify(r));reportId=String(r.data.id);const after=await snapshot(db,admin);assert.ok(after.assets.find(a=>a.id===assetId)!.critical>before.assets.find(a=>a.id===assetId)!.critical);assert.ok(after.pulse<before.pulse);assert.equal((await call('/reports/'+reportId,'PATCH',{status:'Verified'},'citizen')).res.status,403);assert.equal((await call('/reports/'+reportId,'PATCH',{status:'Verified'},'officer')).res.status,403);assert.equal((await call('/reports/'+reportId,'PATCH',{assignedOfficer:'officer'})).res.status,200);assert.equal((await call('/reports/'+reportId,'PATCH',{status:'Verified'},'officer')).res.status,200);const image=await fetch(base+'/api/uploads/'+u.data.id,{headers:{Cookie:sessions.get('officer')!.cookie}});assert.equal(image.status,200);assert.match(image.headers.get('content-type')!,/image\/webp/);});
 await t.test('incident CRUD and safe deletes',async()=>{const r=await call('/incidents','POST',{assetId,description:'Road access closed during test inspection',severity:'High',status:'Open'},'officer');assert.equal(r.res.status,201,JSON.stringify(r));assert.equal((await call('/incidents/'+r.data.id,'PATCH',{status:'Resolved',resolution:'Inspection finished'},'officer')).res.status,200);assert.equal((await call('/assets/'+assetId,'DELETE')).res.status,409);const temporary=await call('/assets','POST',{name:'Removable asset',type:'Water',ward:1,condition:90,pop:50,cost:.2,hazard:5,action:'Inspect'});assert.equal((await call('/assets/'+temporary.data.id,'DELETE')).res.status,200);assert.equal((await call('/assets/'+temporary.data.id)).res.status,404)});
 await t.test('directed deterministic RICE and persisted active overlay',async()=>{const s=await snapshot(db,admin),one=rice(s.assets,s.dependencies,s.wards,['D04'],20);assert.deepEqual(one,rice(s.assets,s.dependencies,s.wards,['D04'],20));for(const asset of ['D04','R07','S02','PHC01'])assert.ok(one.affected.includes(asset));assert.ok(one.pop<=3000&&one.households<=650);const reverse=rice(s.assets,s.dependencies,s.wards,['S02']);assert.ok(!reverse.affected.includes('D04'));const cyclic=[...s.dependencies,{id:'cycle',source:'S02',target:'D04',type:'affects' as const,strength:1,impactWeight:1}];assert.ok(rice(s.assets,cyclic,s.wards,['D04']).affected.length<=s.assets.length);const r=await call('/simulations/failure','POST',{scenario:'D04',rain:20,apply:true});assert.equal(r.res.status,200);assert.ok((await snapshot(db,admin)).simAffected.includes('PHC01'));assert.equal((await call('/simulations/active','DELETE')).res.status,200)});
 await t.test('optimizer respects costs/counts/wards and what-if preserves base records',async()=>{const s=await snapshot(db,admin),input={budget:10,minProjects:2,maxProjects:5,minimumPriority:0};const r=optimize(s.assets,s.interventions,s.wards,input);assert.ok(r.feasible);assert.ok(r.totalCost<=10&&r.projects.length<=5&&r.projects.length>=2);assert.deepEqual(r,optimize(s.assets,s.interventions,s.wards,input));const impossible=optimize(s.assets,s.interventions,s.wards,{...input,budget:.001});assert.equal(impossible.feasible,false);const w=whatIf(s.assets,s.dependencies,s.wards,s.reports,s.incidents,s.weights,{rain:80,population:20,assetId:'D04',condition:-20,capacity:.5});assert.ok(w.after.floodExposure>w.before.floodExposure);assert.ok(w.after.population>w.before.population);const apiResult=await call('/simulations/what-if','POST',{rain:80,population:20,assetId:'D04',condition:-20,capacity:.5});assert.equal(apiResult.res.status,200);assert.deepEqual((await snapshot(db,admin)).assets.find(a=>a.id==='D04'),s.assets.find(a=>a.id==='D04'));assert.equal((await call('/budget/optimize','POST',input)).res.status,200)});
 await t.test('ownership, audit, notifications, search and session invalidation',async()=>{const created=await call('/users','POST',{name:'Second citizen',email:'other@example.test',password:'Second-citizen-password',role:'citizen'});assert.equal(created.res.status,201);const login=await call('/auth/login','POST',{email:'other@example.test',password:'Second-citizen-password'},'other');sessions.set('other',{cookie:login.res.headers.get('set-cookie')!.split(';')[0],csrf:String(login.data.csrf)});const state=await call('/state','GET',undefined,'other');assert.equal((state.data.reports as unknown[]).length,0);assert.equal((await call('/reports/'+reportId,'PATCH',{description:'Unauthorized report editing attempt'},'other')).res.status,403);const logs=await call('/audit');assert.ok((logs.data as unknown as unknown[]).length>0);assert.ok((await call('/notifications')).success);assert.ok((await call('/search?q=Integration')).success);await call('/users/'+created.data.id,'PATCH',{disabled:true});assert.equal((await call('/state','GET',undefined,'other')).res.status,401);await call('/auth/logout','POST',undefined,'citizen');assert.equal((await call('/state','GET',undefined,'citizen')).res.status,401)});
 await new Promise<void>((resolve,reject)=>server.close(e=>e?reject(e):resolve()));await db.close();db=await connect();assert.ok((await snapshot(db,admin)).assets.some(a=>a.id===assetId));assert.ok((await snapshot(db,admin)).reports.some(r=>r.id===reportId));
 }finally{if(server.listening)await new Promise<void>(r=>server.close(()=>r()));await db.close()}
});

