CREATE TABLE IF NOT EXISTS schema_migrations (version integer PRIMARY KEY, applied_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE villages(id text PRIMARY KEY, data jsonb NOT NULL, created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE wards(id text PRIMARY KEY, village_id text NOT NULL REFERENCES villages(id), number integer NOT NULL CHECK(number BETWEEN 1 AND 6), data jsonb NOT NULL, UNIQUE(village_id,number));
CREATE TABLE users(id text PRIMARY KEY, village_id text NOT NULL REFERENCES villages(id), email text NOT NULL UNIQUE, name text NOT NULL, role text NOT NULL CHECK(role IN ('admin','officer','citizen')), password_hash text NOT NULL, disabled boolean NOT NULL DEFAULT false, created_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE sessions(token_hash text PRIMARY KEY, user_id text NOT NULL REFERENCES users(id) ON DELETE CASCADE, csrf text NOT NULL, expires_at timestamptz NOT NULL);
CREATE INDEX sessions_expiry ON sessions(expires_at);
CREATE TABLE assets(id text PRIMARY KEY, village_id text NOT NULL REFERENCES villages(id), ward_id text NOT NULL REFERENCES wards(id), data jsonb NOT NULL CHECK((data->>'condition')::numeric BETWEEN 0 AND 100), created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now());
CREATE INDEX assets_ward ON assets(ward_id);
CREATE INDEX assets_type ON assets((data->>'type'));
CREATE TABLE dependencies(id text PRIMARY KEY, source text NOT NULL REFERENCES assets(id) ON DELETE CASCADE, target text NOT NULL REFERENCES assets(id) ON DELETE CASCADE, type text NOT NULL CHECK(type IN ('depends_on','supplies','protects','serves','connected_to','accessible_by','affects','downstream_of','upstream_of')), strength double precision NOT NULL CHECK(strength>0 AND strength<=1), impact_weight double precision NOT NULL CHECK(impact_weight>0 AND impact_weight<=1), created_at timestamptz NOT NULL DEFAULT now(), CHECK(source<>target), UNIQUE(source,target,type));
CREATE INDEX dependencies_target ON dependencies(target);
CREATE TABLE uploads(id text PRIMARY KEY,user_id text NOT NULL REFERENCES users(id),path text NOT NULL UNIQUE,mime text NOT NULL,size integer NOT NULL CHECK(size>0),created_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE reports(id text PRIMARY KEY,village_id text NOT NULL REFERENCES villages(id),ward_id text NOT NULL REFERENCES wards(id),asset_id text REFERENCES assets(id) ON DELETE SET NULL,user_id text NOT NULL REFERENCES users(id),assigned_officer text REFERENCES users(id),image_id text REFERENCES uploads(id),data jsonb NOT NULL,created_at timestamptz NOT NULL DEFAULT now(),updated_at timestamptz NOT NULL DEFAULT now());
CREATE INDEX reports_asset ON reports(asset_id);
CREATE INDEX reports_owner ON reports(user_id,created_at);
CREATE INDEX reports_assignee ON reports(assigned_officer);
CREATE TABLE incidents(id text PRIMARY KEY,village_id text NOT NULL REFERENCES villages(id),asset_id text NOT NULL REFERENCES assets(id),data jsonb NOT NULL,created_at timestamptz NOT NULL DEFAULT now(),updated_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE incident_assets(incident_id text REFERENCES incidents(id) ON DELETE CASCADE,asset_id text REFERENCES assets(id),PRIMARY KEY(incident_id,asset_id));
CREATE TABLE interventions(id text PRIMARY KEY,village_id text NOT NULL REFERENCES villages(id),asset_id text NOT NULL REFERENCES assets(id),data jsonb NOT NULL,created_at timestamptz NOT NULL DEFAULT now(),updated_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE simulations(id text PRIMARY KEY,user_id text NOT NULL REFERENCES users(id),village_id text NOT NULL REFERENCES villages(id),kind text NOT NULL,input jsonb NOT NULL,result jsonb NOT NULL,created_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE settings(village_id text PRIMARY KEY REFERENCES villages(id),weights jsonb NOT NULL,active_simulation text REFERENCES simulations(id) ON DELETE SET NULL);
CREATE TABLE pulse_history(id bigserial PRIMARY KEY,village_id text NOT NULL REFERENCES villages(id),pulse double precision NOT NULL,reason text NOT NULL,created_at timestamptz NOT NULL DEFAULT now());
CREATE INDEX pulse_date ON pulse_history(village_id,created_at);
CREATE TABLE audit_log(id bigserial PRIMARY KEY,user_id text REFERENCES users(id),village_id text NOT NULL REFERENCES villages(id),action text NOT NULL,entity text NOT NULL,entity_id text,metadata jsonb NOT NULL DEFAULT '{}',created_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE notifications(id bigserial PRIMARY KEY,village_id text NOT NULL REFERENCES villages(id),user_id text REFERENCES users(id),message text NOT NULL,created_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE notification_reads(notification_id bigint REFERENCES notifications(id) ON DELETE CASCADE,user_id text REFERENCES users(id) ON DELETE CASCADE,PRIMARY KEY(notification_id,user_id));
INSERT INTO schema_migrations(version) VALUES (1);
