import type {Asset,Dependency,Ward,Report,Incident,Simulation,Intervention} from '../shared/models.js';
import {defaultWeights} from '../shared/models.js';
export const clamp=(n:number)=>Math.max(0,Math.min(100,n));
const round=(n:number)=>Math.round(n*100)/100;
export function arcs(edges:Dependency[]){return edges.flatMap(e=>{const x={source:e.source,target:e.target,weight:e.strength*e.impactWeight,type:e.type};if(['depends_on','accessible_by','downstream_of'].includes(e.type))return[{...x,source:e.target,target:e.source}];if(e.type==='connected_to')return[x,{...x,source:e.target,target:e.source}];return[x]})}
export function rice(assets:Asset[],edges:Dependency[],wards:Ward[],starters:string[],rain=0,sc='custom'):Simulation{
 const byId=new Map(assets.map(a=>[a.id,a])),links=arcs(edges).sort((a,b)=>a.source.localeCompare(b.source)||a.target.localeCompare(b.target));
 const seen=new Map<string,{depth:number;intensity:number}>(),queue= [...new Set(starters)].sort().filter(x=>byId.has(x));for(const s of queue)seen.set(s,{depth:0,intensity:1});
 const paths:Simulation['paths']=[];
 for(let i=0;i<queue.length;i++){const source=queue[i],v=seen.get(source)!;for(const e of links.filter(e=>e.source===source)){const intensity=v.intensity*e.weight;if(intensity<.1||seen.has(e.target))continue;seen.set(e.target,{depth:v.depth+1,intensity});queue.push(e.target);paths.push({source,target:e.target,depth:v.depth+1,intensity:round(intensity)})}}
 const affected=queue.map(x=>byId.get(x)!),wardIds=new Set(affected.map(a=>a.ward));
 // Asset catchments overlap: take the maximum exposed population in each ward,
 // bounded by that ward's census. Sum only across distinct wards.
 let pop=0,households=0;for(const w of wards){const exposed=Math.min(w.population,Math.max(0,...affected.filter(a=>a.ward===w.number).map(a=>a.pop*seen.get(a.id)!.intensity*(1+Math.max(0,rain)/200))));pop+=exposed;households+=w.population?exposed/w.population*w.households:0;}
 const depth=Math.max(0,...[...seen.values()].map(v=>v.depth)),population=wards.reduce((s,w)=>s+w.population,0);
 return {sc,direct:[...new Set(starters)].sort(),affected:queue,paths,chain:affected.map(a=>[`${seen.get(a.id)!.depth?'Dependency impact':'Initiating failure'} · ${a.name}`,`${a.type} · Ward ${a.ward} · exposure ${Math.round(seen.get(a.id)!.intensity*100)}%`]),depth,pop:Math.round(pop),households:Math.round(households),services:new Set(affected.map(a=>a.type)).size,wards:wardIds.size,impact:round(clamp(pop/Math.max(1,population)*70+depth*5+Math.max(0,rain)*.1)),schools:affected.filter(a=>a.type==='Education').length,healthcare:affected.filter(a=>a.type==='Healthcare').length,waterPoints:affected.filter(a=>a.type==='Water').length,accessibilityChange:-round(affected.filter(a=>a.type==='Road').length/Math.max(1,assets.filter(a=>a.type==='Road').length)*100),label:'SIMULATED — directed graph / ward-capped overlapping catchments'};
}
export function scoreAssets(assets:Asset[],edges:Dependency[],reports:Report[],incidents:Incident[],weights=defaultWeights,affected:string[]=[]){
 const links=arcs(edges),total=Object.values(weights).reduce((a,b)=>a+b,0);
 return assets.map(a=>{const evidence=reports.filter(r=>r.assetId===a.id),open=evidence.filter(r=>!['Resolved','Rejected'].includes(r.status)),incident=incidents.filter(i=>(i.assetId===a.id||i.affectedAssets.includes(a.id))&&i.status!=='Resolved'),downstream=links.filter(e=>e.source===a.id),condition=a.status==='Unavailable'?0:a.condition;
 const factors={condition:100-condition,population:clamp(a.pop/12),service:clamp(downstream.length*20),accessibility:100-a.accessibility,hazard:clamp(a.hazard+incident.length*10+(affected.includes(a.id)?25:0)),evidence:clamp(open.reduce((s,r)=>s+(r.severity==='HIGH'?20:r.severity==='MEDIUM'?12:5),0))};
 const reason=Object.entries(weights).map(([k,v])=>[k,round(factors[k as keyof typeof factors]*v/total)] as [string,number]);const critical=round(reason.reduce((s,[,v])=>s+v,0));
 const confidenceFactors={provenance:a.source==='VERIFIED'?40:a.source==='FIELD REPORTED'?25:15,inspection:a.verifiedAt?25:0,evidence:Math.min(20,evidence.filter(r=>r.status==='Verified'||r.status==='Resolved').length*4),completeness:a.latitude!==null&&a.longitude!==null?15:0};
 return {...a,condition,critical,criticality:critical,risk:affected.includes(a.id)||critical>=65?'High':critical>=40?'Medium':'Low',reports:evidence.length,connections:downstream.map(e=>e.target),reason,confidenceFactors,confidence:Object.values(confidenceFactors).reduce((s,n)=>s+n,0),verified:a.verifiedAt||'Not field verified',cat:({Road:'road',Drainage:'drainage',Water:'water',Education:'education',Healthcare:'health'} as Record<string,string>)[a.type]||'sanitation'};
 });
}
export function pulse(assets:Asset[],reports:Report[],incidents:Incident[],affected:string[]=[]){const categories:Record<string,number>={};for(const[type,label] of [['Water','Water'],['Road','Roads'],['Drainage','Drainage'],['Education','Education'],['Sanitation','Sanitation'],['Healthcare','Health']]){const list=assets.filter(a=>type==='Sanitation'?['Sanitation','Streetlight','Public Facility'].includes(a.type):a.type===type);categories[label]=list.length?round(list.reduce((s,a)=>s+clamp(a.condition-a.critical*.15-(affected.includes(a.id)?20:0)),0)/list.length):0;}const incidentPenalty=Math.min(10,incidents.filter(i=>i.status!=='Resolved').length*.25);const reportPenalty=Math.min(10,reports.filter(r=>!['Resolved','Rejected'].includes(r.status)).length*.08);return{categories,pulse:round(clamp(Object.values(categories).reduce((s,v)=>s+v,0)/6-incidentPenalty-reportPenalty)),factors:{categoryWeight:1/6,incidentPenalty,reportPenalty,missingCategoryScore:0}};}
export interface BudgetOptions {budget:number;minProjects:number;maxProjects:number;ward?:number;category?:string;minimumPriority:number;strategy?:'impact'|'cost'}
export function optimize(assets:Asset[],projects:Intervention[],wards:Ward[],options:BudgetOptions){
 const items=projects.filter(p=>['proposed','approved'].includes(p.status)&&p.cost<=options.budget).flatMap(p=>{const a=assets.find(a=>a.id===p.assetId);return a&&(!options.ward||p.ward===options.ward)&&(!options.category||a.type===options.category)&&a.critical>=options.minimumPriority?[{...p,asset:a,value:round((p.populationBenefit*.4+a.critical*3+p.riskReduction*2+p.serviceImprovement)*(a.confidence/100))}]:[]}).sort((a,b)=>a.id.localeCompare(b.id));
 // Sparse exact 0/1 knapsack in rupees, retaining Pareto frontiers by project
 // count. Costs are in lakhs at the API boundary; no rounding beyond rupees.
 type State={cost:number;value:number;items:typeof items};const states:State[][]=Array.from({length:options.maxProjects+1},()=>[]);states[0]=[{cost:0,value:0,items:[]}];const cap=Math.round(options.budget*100000);
 for(const item of items){for(let k=options.maxProjects;k>=1;k--){const candidates=[...states[k],...states[k-1].filter(s=>s.cost+Math.round(item.cost*100000)<=cap).map(s=>({cost:s.cost+Math.round(item.cost*100000),value:s.value+(options.strategy==='cost'?1/item.cost:item.value),items:[...s.items,item]}))].sort((a,b)=>a.cost-b.cost||b.value-a.value);let best=-Infinity;states[k]=candidates.filter(s=>{if(s.value<=best)return false;best=s.value;return true});}}
 const best=states.slice(options.minProjects).flat().sort((a,b)=>b.value-a.value||a.cost-b.cost)[0];if(!best)return{feasible:false,projects:[],totalCost:0,remainingBudget:options.budget,residents:0,risk:0,services:0,wardCoverage:[],expectedImpact:0,reason:'No combination satisfies the budget and project-count constraints.'};
 const residents=wards.reduce((sum,w)=>sum+Math.min(w.population,Math.max(0,...best.items.filter(p=>p.ward===w.number).map(p=>p.populationBenefit))),0),risk=best.items.length?round(best.items.reduce((s,p)=>s+p.riskReduction,0)/best.items.length):0;
 return{feasible:true,projects:best.items.map(p=>({...p,asset:undefined})),totalCost:best.cost/100000,remainingBudget:round(options.budget-best.cost/100000),residents,risk,services:new Set(best.items.map(p=>p.asset.type)).size,serviceImprovement:best.items.length?round(best.items.reduce((s,p)=>s+p.serviceImprovement,0)/best.items.length):0,wardCoverage:[...new Set(best.items.map(p=>p.ward))],expectedImpact:round(best.value),method:'Exact 0/1 knapsack; ward-max catchments avoid double-counting beneficiaries',factors:{population:.4,criticality:3,riskReduction:2,serviceImprovement:1,confidenceMultiplier:true}};
}
export interface WhatIfOptions{rain:number;population:number;assetId:string;condition:number;capacity:number;newFacility?:{type:Asset['type'];ward:number;latitude:number;longitude:number;capacity:number};relocate?:{assetId:string;latitude:number;longitude:number}}
export function whatIf(assets:Asset[],edges:Dependency[],wards:Ward[],reports:Report[],incidents:Incident[],weights:typeof defaultWeights,input:WhatIfOptions){
 const changed=assets.map(a=>({...a,condition:clamp(a.condition+(a.id===input.assetId?input.condition:0)),capacity:a.capacity*(a.id===input.assetId?input.capacity:1),hazard:clamp(a.hazard+input.rain*.25),pop:Math.round(a.pop*(1+input.population/100)),...(input.relocate?.assetId===a.id?{latitude:input.relocate.latitude,longitude:input.relocate.longitude}:{})}));
 if(input.newFacility){const f=input.newFacility;changed.push({...assets[0],id:'SCENARIO-FACILITY',name:'Proposed facility',type:f.type,ward:f.ward,latitude:f.latitude,longitude:f.longitude,capacity:f.capacity,pop:f.capacity,condition:100,hazard:0,reports:0,connections:[],source:'SIMULATED'});}
 function metrics(list:Asset[],populationFactor:number){const scored=scoreAssets(list,edges,reports,incidents,weights);const distance=(w:Ward,a:Asset)=>Math.hypot((w.latitude-a.latitude)*111,(w.longitude-a.longitude)*111*Math.cos(w.latitude*Math.PI/180));const proximity=(type:string)=>round(wards.reduce((s,w)=>{const facilities=list.filter(a=>a.type===type&&a.status!=='Unavailable');return s+w.population*(facilities.length?Math.max(0,1-Math.min(...facilities.map(a=>distance(w,a)))/5):0)},0)/Math.max(1,wards.reduce((s,w)=>s+w.population,0))*100);const population=wards.reduce((s,w)=>s+w.population,0)*populationFactor;return{pulse:pulse(scored,reports,incidents).pulse,waterCoverage:round(Math.min(100,list.filter(a=>a.type==='Water').reduce((s,a)=>s+a.capacity*a.condition/100,0)/Math.max(1,population)*100)),floodExposure:round(list.filter(a=>a.type==='Drainage').reduce((s,a)=>s+a.hazard*(1-a.condition/100),0)/Math.max(1,list.filter(a=>a.type==='Drainage').length)),schoolAccessibility:proximity('Education'),healthcareProximity:proximity('Healthcare'),accessibility:round(list.filter(a=>a.type==='Road').reduce((s,a)=>s+a.condition,0)/Math.max(1,list.filter(a=>a.type==='Road').length)),infrastructureRisk:round(scored.reduce((s,a)=>s+a.critical,0)/Math.max(1,scored.length)),population:Math.round(population)};}
 const before=metrics(assets,1),after=metrics(changed,1+input.population/100);return{before,after,delta:Object.fromEntries(Object.keys(before).map(k=>[k,round(after[k as keyof typeof after]-before[k as keyof typeof before])])),label:'SIMULATED — capacity-weighted supply and 5 km schematic service catchments; base records unchanged'};
}
