import {readFile} from 'node:fs/promises';
import {assetSchema,defaultWeights} from '../shared/models.js';
import type {AssetInput} from '../shared/models.js';
import {hashPassword} from './auth.js';
import type {DB} from './db.js';
import {snapshot,VILLAGE} from './services.js';
type SeedAsset=AssetInput&{id:string;connections:string[]};
export async function seed(db:DB){
 if((await db.query('SELECT id FROM villages LIMIT 1')).length)return false;
 const password=process.env.SEED_PASSWORD;if(!password||password.length<12)throw new Error('Set SEED_PASSWORD to at least 12 characters before seeding.');
 const hash=await hashPassword(password),assets=JSON.parse(await readFile('server/seed-assets.json','utf8')) as SeedAsset[];
 await db.transaction(async tx=>{
 await tx.query('INSERT INTO villages(id,data) VALUES($1,$2)',[VILLAGE,JSON.stringify({name:'Adarsh Gram',code:'DEMO-001',district:'Simulated District',state:'Demo State',population:3000,households:650,area:6.8,latitude:23.0125,longitude:78.0125})]);
 for(let w=1;w<=6;w++)await tx.query('INSERT INTO wards(id,village_id,number,data) VALUES($1,$2,$3,$4)',[`ward-${w}`,VILLAGE,w,JSON.stringify({number:w,name:`Ward ${w}`,population:[450,480,520,620,460,470][w-1],households:[98,104,113,134,100,101][w-1],latitude:23.004+w*.0025,longitude:78.003+w*.0025,geometry:[[10+(w-1)%3*28,15+Math.floor((w-1)/3)*35],[36+(w-1)%3*28,15+Math.floor((w-1)/3)*35],[36+(w-1)%3*28,48+Math.floor((w-1)/3)*35],[10+(w-1)%3*28,48+Math.floor((w-1)/3)*35]]})]);
 for(const role of ['admin','officer','citizen'])await tx.query('INSERT INTO users(id,village_id,email,name,role,password_hash) VALUES($1,$2,$3,$4,$5,$6)',[role,VILLAGE,`${role}@gram-pulse.demo`,`${role[0].toUpperCase()+role.slice(1)} demo`,role,hash]);
 for(const a of assets){const data=assetSchema.parse({name:a.name,type:a.type,ward:a.ward,condition:a.condition,pop:a.pop,cost:Math.round(a.cost*100)/100,hazard:a.hazard,action:a.action,latitude:23+a.y/100*.025,longitude:78+a.x/100*.025,x:a.x,y:a.y,capacity:Math.round(a.pop*1.15),accessibility:Math.round(100-a.hazard*.6),source:'SIMULATED'});await tx.query('INSERT INTO assets(id,village_id,ward_id,data) VALUES($1,$2,$3,$4)',[a.id,VILLAGE,`ward-${a.ward}`,JSON.stringify(data)]);await tx.query('INSERT INTO interventions(id,village_id,asset_id,data) VALUES($1,$2,$3,$4)',[`PR-${a.id}`,VILLAGE,a.id,JSON.stringify({assetId:a.id,ward:a.ward,name:a.action,cost:data.cost,riskReduction:Math.round((100-a.condition)*.65),serviceImprovement:Math.round((100-a.condition)*.5),populationBenefit:a.pop,status:'proposed',timeline:'30–90 days after field assessment'})]);}
 const edges=new Map<string,{source:string;target:string;type:string}>();const add=(source:string,target:string,type:string)=>{if(source!==target&&assets.some(a=>a.id===target))edges.set(`${source}-${target}-${type}`,{source,target,type})};
 // Model actual direction: drains protect roads, roads provide service access,
 // tanks supply points. Remove prototype's accidental all-to-all reverse links.
 for(const a of assets){if(a.type==='Drainage'){const road=assets.find(b=>b.type==='Road'&&b.ward===a.ward);if(road)add(a.id,road.id,'protects');}if(a.type==='Education'||a.type==='Healthcare'||a.type==='Public Facility'){const road=assets.find(b=>b.type==='Road'&&b.ward===a.ward)||assets.find(b=>b.id==='R07');if(road)add(road.id,a.id,'serves');}if(a.type==='Water'&&!/^W0/.test(a.id))add(a.ward<3?'W01':a.ward<5?'W02':'W03',a.id,'supplies');}
 add('D04','R07','protects');add('R07','S02','serves');add('R07','PHC01','serves');add('R07','W02','affects');
 for(const [key,e]of edges)await tx.query('INSERT INTO dependencies(id,source,target,type,strength,impact_weight) VALUES($1,$2,$3,$4,$5,$6)',[key,e.source,e.target,e.type,1,e.type==='supplies'?1:.85]);
 for(let i=0;i<56;i++){const a=assets[i%10],date=new Date(Date.UTC(2026,9,8,12)-(i+2)*86400000).toISOString();await tx.query('INSERT INTO reports(id,village_id,ward_id,asset_id,user_id,assigned_officer,data,created_at) VALUES($1,$2,$3,$4,$5,$6,$7,$8)',[`DR-${String(i+1).padStart(4,'0')}`,VILLAGE,`ward-${a.ward}`,a.id,'citizen','officer',JSON.stringify({category:a.type,title:`${a.name} inspection observation`,description:`Synthetic historical ${a.type.toLowerCase()} condition observation near ${a.name}.`,ward:a.ward,severity:i%4===0?'HIGH':i%3===0?'MEDIUM':'LOW',confidence:55,status:i%4===0?'Verified':'Pending verification',timestamp:date,synthetic:true,resolutionNotes:'',verifiedAt:null,classificationMethod:'Seeded demonstration report',latitude:23+a.y*.00025,longitude:78+a.x*.00025}),date]);}
 for(let i=0;i<15;i++){const a=assets[(i*7+2)%assets.length],date=new Date(Date.UTC(2026,9,8,12)-(i+1)*3*86400000).toISOString(),status=i%3===0?'Open':'Resolved';await tx.query('INSERT INTO incidents(id,village_id,asset_id,data,created_at) VALUES($1,$2,$3,$4,$5)',[`INC-${i+1}`,VILLAGE,a.id,JSON.stringify({assetId:a.id,category:a.type,severity:i%4===0?'High':'Medium',status,description:`Synthetic historical interruption at ${a.name}.`,cause:'Seasonal exposure and condition deterioration',resolution:status==='Resolved'?'Inspection and corrective work recorded':'',date,endTime:status==='Resolved'?date:null,affectedAssets:[a.id],affectedPopulation:a.pop,cost:a.cost,response:'Field inspection'}),date]);await tx.query('INSERT INTO incident_assets VALUES($1,$2)',[`INC-${i+1}`,a.id]);}
 await tx.query('INSERT INTO settings(village_id,weights) VALUES($1,$2)',[VILLAGE,JSON.stringify(defaultWeights)]);
 const s=await snapshot(tx,{id:'admin',villageId:VILLAGE,name:'Admin',email:'admin@gram-pulse.demo',role:'admin',disabled:false});await tx.query('INSERT INTO pulse_history(village_id,pulse,reason) VALUES($1,$2,$3)',[VILLAGE,s.pulse,'Initial database seed — SIMULATED / DEMO DATA']);
 });return true;
}
