import type {DB} from './db.js';
import type {Asset,Dependency,Report,Incident,Intervention,Ward,Village,User,Snapshot,Simulation} from '../shared/models.js';
import {defaultWeights} from '../shared/models.js';
import {scoreAssets,pulse} from './engines.js';
export const VILLAGE='adarsh';
export class AppError extends Error{constructor(public status:number,public code:string,message:string){super(message)}}
export async function records<T>(db:DB,table:'assets'|'wards'|'villages'|'incidents'|'interventions'){return db.query<T>(`SELECT data || jsonb_build_object('id',id) ${table==='assets'?`|| jsonb_build_object('villageId',village_id,'createdAt',created_at,'updatedAt',updated_at)`:''} AS record FROM ${table} ORDER BY id`).then(rows=>rows.map(r=>(r as {record:T}).record));}
export async function getReports(db:DB){return db.query<{record:Report}>(`SELECT data || jsonb_build_object('id',id,'assetId',asset_id,'userId',user_id,'assignedOfficer',assigned_officer,'imageId',image_id,'photo',CASE WHEN image_id IS NULL THEN '' ELSE '/api/uploads/'||image_id END) AS record FROM reports ORDER BY created_at DESC`).then(rows=>rows.map(r=>r.record))}
export async function snapshot(db:DB,user:User):Promise<Snapshot>{
 const [raw,wards,villages,dependencies,reports,incidents,interventions,settings,history]=await Promise.all([records<Asset>(db,'assets'),records<Ward>(db,'wards'),records<Village>(db,'villages'),db.query<Dependency>('SELECT id,source,target,type,strength,impact_weight AS "impactWeight" FROM dependencies ORDER BY id'),getReports(db),records<Incident>(db,'incidents'),records<Intervention>(db,'interventions'),db.query<{weights:typeof defaultWeights;result:Simulation|null}>(`SELECT weights,result FROM settings LEFT JOIN simulations ON simulations.id=settings.active_simulation WHERE settings.village_id=$1`,[user.villageId]),db.query<{date:string;pulse:number;reason:string}>('SELECT created_at AS date,pulse,reason FROM pulse_history WHERE village_id=$1 ORDER BY id DESC LIMIT 30',[user.villageId])]);
 const simulation=settings[0]?.result||null,weights=settings[0]?.weights||defaultWeights,affected=simulation?.affected||[],assets=scoreAssets(raw,dependencies,reports,incidents,weights,affected),health=pulse(assets,reports,incidents,affected);
 return{village:villages[0],wards,assets,dependencies,reports:reports.filter(r=>user.role==='admin'||(user.role==='officer'?r.assignedOfficer===user.id:r.userId===user.id)),incidents,interventions,weights,simAffected:affected,simulation,pulseHistory:history.reverse(),...health,user,revision:String(history.at(-1)?.date||'0')};
}
export async function audit(db:DB,user:User,action:string,entity:string,entityId:string|null,metadata:Record<string,unknown>={}){await db.query('INSERT INTO audit_log(user_id,village_id,action,entity,entity_id,metadata) VALUES($1,$2,$3,$4,$5,$6)',[user.id,user.villageId,action,entity,entityId,JSON.stringify(metadata)]);}
export async function changed(db:DB,user:User,action:string,entity:string,entityId:string|null,privateUser:string|null=null){await audit(db,user,action,entity,entityId);const s=await snapshot(db,{...user,role:'admin'});await db.query('INSERT INTO pulse_history(village_id,pulse,reason) VALUES($1,$2,$3)',[user.villageId,s.pulse,action]);await db.query('INSERT INTO notifications(village_id,user_id,message) VALUES($1,$2,$3)',[user.villageId,privateUser,`${action}${entityId?' · '+entityId:''}`]);}
export async function requireAsset(db:DB,id:string,villageId=VILLAGE){const rows=await db.query<{data:Asset}>('SELECT data FROM assets WHERE id=$1 AND village_id=$2',[id,villageId]);if(!rows[0])throw new AppError(404,'ASSET_NOT_FOUND','Infrastructure asset was not found.');return {...rows[0].data,id};}
export async function classify(db:DB,category:string,description:string,ward:number,assetId:string|null){const severe=/blocked|collapse|unsafe|no water|flood|emergency|broken/i.test(description),medium=/leak|damage|intermittent|repair/i.test(description);const type=/drain|waterlog|flood/i.test(description)?'Drainage':/road|pothole|access/i.test(description)?'Road':/pump|tank|water/i.test(description)?'Water':category;if(!assetId){const found=await db.query<{id:string}>("SELECT id FROM assets WHERE ward_id=$1 AND data->>'type'=$2 ORDER BY id LIMIT 1",[`ward-${ward}`,type]);assetId=found[0]?.id||null;}return{assetId,severity:severe?'HIGH':medium?'MEDIUM':'LOW',confidence:severe?70:55,classificationMethod:'Deterministic keyword triage, not trained AI; field verification required'};}
