import { z } from 'zod';
export const id = z.string().regex(/^[A-Za-z0-9_-]{1,80}$/);
const text = z.string().trim().min(1).max(200);
const score = z.number().min(0).max(100);
export const roles = ['admin','officer','citizen'] as const;
export type Role = typeof roles[number];
export interface User {id:string;name:string;email:string;role:Role;villageId:string;disabled:boolean}
export const assetSchema = z.object({name:text,type:z.enum(['Road','Drainage','Water','Education','Healthcare','Sanitation','Streetlight','Public Facility']),ward:z.number().int().min(1).max(6),condition:score,pop:z.number().int().min(0).max(1000000),cost:z.number().positive().max(100000),hazard:score,action:text,latitude:z.number().min(-90).max(90).default(23.012),longitude:z.number().min(-180).max(180).default(78.012),x:score.default(50),y:score.default(50),capacity:z.number().min(0).max(10000000).default(100),accessibility:score.default(70),status:z.enum(['Operational','Degraded','Unavailable','Proposed','Retired']).default('Operational'),source:z.enum(['SIMULATED','FIELD REPORTED','VERIFIED','MODELLED','PREDICTED']).default('FIELD REPORTED'),verifiedAt:z.iso.datetime().nullable().default(null),installationDate:z.iso.date().nullable().default(null),maintenanceDate:z.iso.date().nullable().default(null),age:z.number().min(0).max(500).default(0),geometry:z.array(z.tuple([z.number().min(-180).max(180),z.number().min(-90).max(90)])).max(1000).default([])}).strict();
export type AssetInput=z.infer<typeof assetSchema>;
export interface Asset extends AssetInput {id:string;villageId:string;createdAt:string;updatedAt:string;cat:string;critical:number;criticality:number;risk:string;confidence:number;reports:number;connections:string[];reason:[string,number][];verified:string;confidenceFactors:Record<string,number>}
export const relationshipTypes=['depends_on','supplies','protects','serves','connected_to','accessible_by','affects','downstream_of','upstream_of'] as const;
export const dependencySchema=z.object({source:id,target:id,type:z.enum(relationshipTypes),strength:z.number().min(.01).max(1).default(1),impactWeight:z.number().min(.01).max(1).default(1)}).strict().refine(v=>v.source!==v.target,'Self dependencies are not allowed');
export type Dependency=z.infer<typeof dependencySchema>&{id:string};
export const reportSchema=z.object({name:z.string().trim().max(100).optional(),category:text,title:text.optional(),description:z.string().trim().min(8).max(2000),ward:z.number().int().min(1).max(6),assetId:id.nullable().default(null),imageId:id.nullable().default(null),latitude:z.number().min(-90).max(90).nullable().default(null),longitude:z.number().min(-180).max(180).nullable().default(null)}).strict();
export const reportPatch=z.object({status:z.enum(['Pending verification','Verified','Assigned','In Progress','Resolved','Rejected']).optional(),assignedOfficer:id.nullable().optional(),resolutionNotes:z.string().max(2000).optional(),description:z.string().min(8).max(2000).optional()}).strict();
export interface Report extends z.infer<typeof reportSchema>{id:string;userId:string;status:string;severity:string;confidence:number;timestamp:string;synthetic:boolean;assignedOfficer:string|null;resolutionNotes:string;photo:string;verifiedAt:string|null;classificationMethod:string}
export const incidentSchema=z.object({assetId:id,category:text.optional(),severity:z.enum(['High','Medium','Low']),status:z.enum(['Open','Investigating','Assigned','In Progress','Resolved']),description:z.string().trim().min(8).max(2000),cause:z.string().max(1000).default('Pending investigation'),resolution:z.string().max(2000).default(''),date:z.iso.datetime().optional(),endTime:z.iso.datetime().nullable().default(null),affectedAssets:z.array(id).max(200).default([]),response:z.string().max(2000).default('')}).strict();
export interface Incident extends z.infer<typeof incidentSchema>{id:string;date:string;affectedPopulation:number;cost:number}
export const interventionSchema=z.object({assetId:id,ward:z.number().int().min(1).max(6),name:text,cost:z.number().positive().max(100000),riskReduction:score,serviceImprovement:score,populationBenefit:z.number().int().min(0).max(1000000),status:z.enum(['proposed','approved','in_progress','completed','rejected']).default('proposed'),timeline:z.string().max(200).default('Field assessment required')}).strict();
export interface Intervention extends z.infer<typeof interventionSchema>{id:string}
export const defaultWeights={condition:.22,population:.20,service:.18,accessibility:.15,hazard:.15,evidence:.10};
export const weightsSchema=z.object({condition:score,population:score,service:score,accessibility:score,hazard:score,evidence:score}).strict().refine(v=>Object.values(v).some(x=>x>0),'At least one weight must be positive');
export interface Ward{id:string;number:number;name:string;population:number;households:number;latitude:number;longitude:number;geometry:number[][]}
export interface Village{id:string;name:string;code:string;district:string;state:string;population:number;households:number;area:number;latitude:number;longitude:number}
export interface Simulation {sc:string;affected:string[];direct:string[];chain:[string,string][];paths:{source:string;target:string;depth:number;intensity:number}[];depth:number;pop:number;households:number;services:number;wards:number;impact:number;schools:number;healthcare:number;waterPoints:number;accessibilityChange:number;label:string}
export interface Snapshot {village:Village;wards:Ward[];assets:Asset[];dependencies:Dependency[];reports:Report[];incidents:Incident[];interventions:Intervention[];weights:typeof defaultWeights;simAffected:string[];simulation:Simulation|null;pulseHistory:{date:string;pulse:number;reason:string}[];pulse:number;categories:Record<string,number>;user:User;revision:string}
export type ApiResult<T>={success:true;data:T;pagination?:{page:number;pageSize:number;total:number}}|{success:false;error:{code:string;message:string;requestId?:string}};
